[package]
name = "OxyLisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[toolchain]
channel = "nightly"

[dependencies]
regex = "1"
anyhow = "1.0"
log = "0.4"
env_logger = "0.9.0"
